create table trabajador (id integer primary key, nombre varchar2(20), sueldo_base float);
create table respaldo (id integer primary key, nombre varchar2(20), sueldo_base float);

CREATE OR REPLACE PROCEDURE CONTAR(NUMERO OUT INTEGER)
AS
BEGIN
SELECT COUNT(*) INTO NUMERO FROM TRABAJADOR;

DBMS_OUTPUT.PUT_LINE('ENCONTRADOS  '||NUMERO);
END;
/

CREATE OR REPLACE PROCEDURE COPIAR 
AS
CURSOR CUR_TRABAJADOR IS SELECT * FROM TRABAJADOR;
BEGIN
FOR REC IN CUR_TRABAJADOR LOOP
INSERT INTO RESPALDO VALUES(REC.ID, REC.NOMBRE,REC.SUELDO_BASE);
END LOOP;
END;
/

CREATE OR REPLACE TRIGGER DISP_TRABAJADOR BEFORE INSERT ON TRABAJADOR FOR EACH ROW
DECLARE
VALOR INTEGER;
BEGIN
CONTAR(VALOR);
IF  VALOR = 3 THEN
COPIAR();
DELETE FROM TRABAJADOR;
END IF;
END;
/

INSERT INTO TRABAJADOR VALUES(1,'PAQUITO',5000);
INSERT INTO TRABAJADOR VALUES(2,'JUANITO',2000);
INSERT INTO TRABAJADOR VALUES(3,'PEDRITO',1000);

SELECT *FROM TRABAJADOR;

INSERT INTO TRABAJADOR VALUES(1,'FERNANDITO',100);

SELECT *FROM RESPALDO; 
SELECT *FROM TRABAJADOR;
